// Generated by gencpp from file package_one/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PACKAGE_ONE_MESSAGE_ADDTWOINTS_H
#define PACKAGE_ONE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <package_one/AddTwoIntsRequest.h>
#include <package_one/AddTwoIntsResponse.h>


namespace package_one
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace package_one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::package_one::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::package_one::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::package_one::AddTwoInts > {
  static const char* value()
  {
    return "package_one/AddTwoInts";
  }

  static const char* value(const ::package_one::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::package_one::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::package_one::AddTwoInts >
template<>
struct MD5Sum< ::package_one::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::package_one::AddTwoInts >::value();
  }
  static const char* value(const ::package_one::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::package_one::AddTwoIntsRequest> should match
// service_traits::DataType< ::package_one::AddTwoInts >
template<>
struct DataType< ::package_one::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::package_one::AddTwoInts >::value();
  }
  static const char* value(const ::package_one::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::package_one::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::package_one::AddTwoInts >
template<>
struct MD5Sum< ::package_one::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::package_one::AddTwoInts >::value();
  }
  static const char* value(const ::package_one::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::package_one::AddTwoIntsResponse> should match
// service_traits::DataType< ::package_one::AddTwoInts >
template<>
struct DataType< ::package_one::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::package_one::AddTwoInts >::value();
  }
  static const char* value(const ::package_one::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGE_ONE_MESSAGE_ADDTWOINTS_H
